name: Build Rust Program
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build/Test Rust binary
      run: cargo build --verbose 
    - name: Run tests
      run: cargo test --verbose

      # For storing artifacts and enumeration based on run number
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: hello-rust${{ github.run_number }}
        path: target/debug/hello_world
    
    - name: Login to Github Container Registry
      uses: docker/login-action@v1
      with: 
        registry: ghcr.io
        username: ${{ secrets.WORKFLOW_USERNAME }}
        password: ${{ secrets.WORKFLOW_TOKEN }}
  
    - name: Build Run Push Container
      run: | 
          ls -l
          docker build . --tag ghcr.io/themichael/espresso-rust-app:latest
          docker run ghcr.io/themichael/espresso-rust-app:latest
          docker push ghcr.io/themichael/espresso-rust-app:latest